### ISSUE TITLE
Beta Branch Upgrade Failure on HASSOS

### ISSUE THREAD

**Issue by 1h8fulkat** [Apipa169/Assistant-Relay-for-Hassio#50] opened 2020-10-23 14:02 UTC
**Describe the bug**
I am getting the following error when clicking "upgrade" on the HASSOS Supervisor

> 20-10-23 13:59:03 ERROR (SyncWorker_7) [supervisor.docker.interface] Can't install 6a3d001f/amd64-addon-assistant_relay_beta:4.0.0b2 -> 404 Client Error: Not Found ("pull access denied for 6a3d001f/amd64-addon-assistant_relay_beta, repository does not exist or may require 'docker login': denied: requested access to the resource is denied").

**To Reproduce**
1. Go to HASSOS Supervisor
2. Click on Asisstant Relay BETA Add-On
3. Click on "Update" under Assistant Relay BETA 4.0.0b2 is available - You are currently running version 0.9b

**Expected behavior**
I expect the container image to upgrade, but it doesn't do anything on the GUI and throws the error above in the logs.

**System (please complete the following information):**
Hassio version:  4.13
System:  HassOS

**Comment by Apipa169** [comment] 2020-10-26 16:34
I can't reproduce this. Maybe there was an issue with DockerHub at the time you tried to update.

Please note that the beta is not very stable, consider using the normal release for now.

**Comment by Apipa169** [comment] 2020-11-23 15:07
Closing it for now, feel free to re open if you're still having this issue.

**Closed by Apipa169** 2020-11-23 15:07 UTC
