### ISSUE TITLE
adding user not working?

### ISSUE THREAD

**Issue by metter** [Apipa169/Assistant-Relay-for-Hassio#12] opened 2019-12-11 07:57 UTC
When I try to add a user on the assistant relay page (port 3000), this happens:
Step 1: I enter user name and add the JSON file.
Step 2: The browser opens an EMPTY pop up page (?), while the original page moves on to step 2 , asking me to enter the auth code - which I dont have at this point.

It is not clear to me what actually is SUPPOSED to happen during the process. I assume the pop up page should display googles auth2 consent screen? I do have that setup in cloud console, but I only get an empty pop up page with no URL. I tried this on 3 different systems and browsers.

Thank you for your help

**Comment by Apipa169** [comment] 2019-12-11 08:06
Which version of the add-on are you running?

**Comment by metter** [comment] 2019-12-11 08:18
version 0.7.2

*Markus Etter <markus.etter@gmail.com>* // Regisseur // +41 (0)78 632 87 57
// www.markusetter.com

**Comment by metter** [comment] 2019-12-11 08:36
I went ahead entering some random numbers in the auth response box to see where it leads.
Assistant Relay moves to the "home" page, saying: "no responses yet".


`0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:50)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:97)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:97)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:97)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | Assistant Relay Server Initialized
0|www  | Visit http://172.30.33.0:3000 in a browser to configure
0|www  | GET /static/css/2.25de4381.chunk.css 304 16.346 ms - -
0|www  | GET / 304 18.520 ms - -
0|www  | GET /android-icon-192x192.png 304 22.016 ms - -
0|www  | GET /static/js/main.5f6acfb3.chunk.js 304 25.485 ms - -
0|www  | GET /favicon-32x32.png 304 28.702 ms - -
0|www  | GET /favicon-96x96.png 304 31.517 ms - -
0|www  | GET /static/js/2.e91f5ff5.chunk.js 304 2.202 ms - -
0|www  | GET /favicon-16x16.png 304 5.481 ms - -
0|www  | POST /server/userCount 200 149.125 ms - 10
0|www  | POST /server/getResponses 200 27.469 ms - 16
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.auth (/assistant_relay/helpers/auth.js:11:97)
0|www  |     at /assistant_relay/routes/server.js:41:23
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  | POST /server/addUser 200 24.076 ms - 2
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.auth (/assistant_relay/helpers/auth.js:11:97)
0|www  |     at /assistant_relay/routes/server.js:41:23
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  | POST /server/addUser 200 30.407 ms - 2
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.auth (/assistant_relay/helpers/auth.js:11:97)
0|www  |     at /assistant_relay/routes/server.js:41:23
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  | POST /server/addUser 200 29.345 ms - 2
0|www  | POST /server/getConfig 200 25.864 ms - 125
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.auth (/assistant_relay/helpers/auth.js:11:97)
0|www  |     at /assistant_relay/routes/server.js:41:23
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  | POST /server/addUser 200 25.234 ms - 2
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.processTokens (/assistant_relay/helpers/auth.js:26:97)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/routes/server.js:52:20
0|www  | POST /server/processOAuth 200 75.959 ms - -
0|www  | POST /server/getResponses 200 23.362 ms - 16
0|www  | TypeError: Cannot read property 'getRequestHeaders' of undefined
0|www  |     at getAuthorizationHeaderFromGoogleCredential (/assistant_relay/node_modules/grpc/src/credentials.js:188:32)
0|www  |     at /assistant_relay/node_modules/grpc/src/credentials.js:219:5
0|www  |     at /assistant_relay/node_modules/grpc/src/credentials.js:166:5
0|www  | TypeError: Cannot read property 'client_id' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:50)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | TypeError: Cannot read property 'client_id' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:50)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | TypeError: Cannot read property 'client_id' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:50)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:97)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:97)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:97)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:97)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:97)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:97)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:97)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | Assistant Relay Server Initialized
0|www  | Visit http://172.30.33.0:3000 in a browser to configure`

**Comment by Apipa169** [comment] 2019-12-11 10:48
The pop up should not be empty, this should be a google page to retrieve an auth code.

I’ll come back to you if I’m able to test.

Just to double check: if you restart the add-on, which version of AR is displayed in the logs? Should be v3.1.3

**Comment by metter** [comment] 2019-12-11 11:01
Yes its 3.1.3.

Thanks for checking


> Assistant Relay is now starting...
>
> > assistant-relay@3.1.3 start /assistant_relay
> > pm2 start ./bin/www && pm2 log www
>
>
>                         -------------
>
> __/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
>  _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
>   _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
>    _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
>     _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
>      _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
>       _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
>        _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
>         _\///______________\///______________\///__\///////////////__
>
>
>                           Runtime Edition
>
>         PM2 is a Production Process Manager for Node.js applications
>                      with a built-in Load Balancer.
>
>                 Start and Daemonize any application:
>                 $ pm2 start app.js
>
>                 Load Balance 4 instances of api.js:
>                 $ pm2 start api.js -i 4
>
>                 Monitor in production:
>                 $ pm2 monitor
>
>                 Make pm2 auto-boot at server restart:
>                 $ pm2 startup
>
>                 To go further checkout:
>                 http://pm2.io/
>
>
>                         -------------
>
> [PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
> [PM2] PM2 Successfully daemonized
> [PM2] Starting /assistant_relay/bin/www in fork_mode (1 instance)
> [PM2] Done.
> ┌─────┬──────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
> │ id  │ name │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
> ├─────┼──────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
> │ 0   │ www  │ default     │ 3.1.3   │ fork    │ 50       │ 0s     │ 0    │ online    │ 0%       │ 15.7mb   │ root     │ disabled │
> └─────┴──────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
> [TAILING] Tailing last 15 lines for [www] process (change the value with --lines option)
> /root/.pm2/logs/www-out.log last 15 lines:
> /root/.pm2/logs/www-error.log last 15 lines:
>
>

**Comment by Apipa169** [comment] 2019-12-11 19:49
It was an issue in AR v3.1, but now thats all solved and I'm not able to reproduce it in the newest release. I have tried Safari, Chrome and Firefox, all did what was supposed to happen.

Only think where I can think of at the moment is that your json file is not valid / not the correct one.

**Comment by metter** [comment] 2019-12-12 06:08
ok, I didnt spot that in the documentation, so I assumed it is going to be a web client credential (with JSON). Service account credentials and API key are not provided with a JSON file. I have now tried various credential options on cloud console that give me a JSON file, but all with the same result.
What Google Cloud credentials exactly are needed to set up Assistant Relay?

**Comment by Apipa169** [comment] 2019-12-12 07:06
Try these steps:



- Follow this guide:   https://developers.google.com/assistant/sdk/guides/service/python/embed/config-dev-project-and-account 
and come back once Step 5 is complete
- Now the Assistant API is enabled, click Credentials in the left hand menu
- On this page, select Create Credentials, and choose OAuth client ID
- Select Other as the application type and give it a name such as Assistant Relay Client. Then click create
- You'll get a popup, but just click OK to close this
- Back on the credential page, click the download icon next to the new credential you made. Save it somewhere safe
- Now click Configure Consent Screen
Give the application a name such as Assistant Relay, add an email under Support Email and click Save

**Comment by metter** [comment] 2019-12-12 10:09
I didnt have actions set up. Sorry.
Now the pop up offers the consent screen. So all seems good.
Ill have a go at testing broadcasting tonight.

M

**Closed** 2019-12-12 10:14 UTC

**Comment by Apipa169** [comment] 2019-12-12 14:41
Great!
